require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Contest3rdsController do

  # This should return the minimal set of attributes required to create a valid
  # Contest3rd. As you add validations to Contest3rd, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "a_score" => "1" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Contest3rdsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all contest3rds as @contest3rds" do
      contest3rd = Contest3rd.create! valid_attributes
      get :index, {}, valid_session
      assigns(:contest3rds).should eq([contest3rd])
    end
  end

  describe "GET show" do
    it "assigns the requested contest3rd as @contest3rd" do
      contest3rd = Contest3rd.create! valid_attributes
      get :show, {:id => contest3rd.to_param}, valid_session
      assigns(:contest3rd).should eq(contest3rd)
    end
  end

  describe "GET new" do
    it "assigns a new contest3rd as @contest3rd" do
      get :new, {}, valid_session
      assigns(:contest3rd).should be_a_new(Contest3rd)
    end
  end

  describe "GET edit" do
    it "assigns the requested contest3rd as @contest3rd" do
      contest3rd = Contest3rd.create! valid_attributes
      get :edit, {:id => contest3rd.to_param}, valid_session
      assigns(:contest3rd).should eq(contest3rd)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Contest3rd" do
        expect {
          post :create, {:contest3rd => valid_attributes}, valid_session
        }.to change(Contest3rd, :count).by(1)
      end

      it "assigns a newly created contest3rd as @contest3rd" do
        post :create, {:contest3rd => valid_attributes}, valid_session
        assigns(:contest3rd).should be_a(Contest3rd)
        assigns(:contest3rd).should be_persisted
      end

      it "redirects to the created contest3rd" do
        post :create, {:contest3rd => valid_attributes}, valid_session
        response.should redirect_to(Contest3rd.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved contest3rd as @contest3rd" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contest3rd.any_instance.stub(:save).and_return(false)
        post :create, {:contest3rd => { "a_score" => "invalid value" }}, valid_session
        assigns(:contest3rd).should be_a_new(Contest3rd)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Contest3rd.any_instance.stub(:save).and_return(false)
        post :create, {:contest3rd => { "a_score" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested contest3rd" do
        contest3rd = Contest3rd.create! valid_attributes
        # Assuming there are no other contest3rds in the database, this
        # specifies that the Contest3rd created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Contest3rd.any_instance.should_receive(:update_attributes).with({ "a_score" => "1" })
        put :update, {:id => contest3rd.to_param, :contest3rd => { "a_score" => "1" }}, valid_session
      end

      it "assigns the requested contest3rd as @contest3rd" do
        contest3rd = Contest3rd.create! valid_attributes
        put :update, {:id => contest3rd.to_param, :contest3rd => valid_attributes}, valid_session
        assigns(:contest3rd).should eq(contest3rd)
      end

      it "redirects to the contest3rd" do
        contest3rd = Contest3rd.create! valid_attributes
        put :update, {:id => contest3rd.to_param, :contest3rd => valid_attributes}, valid_session
        response.should redirect_to(contest3rd)
      end
    end

    describe "with invalid params" do
      it "assigns the contest3rd as @contest3rd" do
        contest3rd = Contest3rd.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contest3rd.any_instance.stub(:save).and_return(false)
        put :update, {:id => contest3rd.to_param, :contest3rd => { "a_score" => "invalid value" }}, valid_session
        assigns(:contest3rd).should eq(contest3rd)
      end

      it "re-renders the 'edit' template" do
        contest3rd = Contest3rd.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Contest3rd.any_instance.stub(:save).and_return(false)
        put :update, {:id => contest3rd.to_param, :contest3rd => { "a_score" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested contest3rd" do
      contest3rd = Contest3rd.create! valid_attributes
      expect {
        delete :destroy, {:id => contest3rd.to_param}, valid_session
      }.to change(Contest3rd, :count).by(-1)
    end

    it "redirects to the contest3rds list" do
      contest3rd = Contest3rd.create! valid_attributes
      delete :destroy, {:id => contest3rd.to_param}, valid_session
      response.should redirect_to(contest3rds_url)
    end
  end

end
